upgrade version 19.6.0

diff --git a/src/test/run-selftest-pg b/src/test/run-selftest-pg
--- a/src/test/run-selftest-pg
+++ b/src/test/run-selftest-pg
@@ -107,3 +107,10 @@ else
 fi
 
 ./hcnet-core test $HCNET_CORE_TEST_PARAMS --base-instance $BASE_INSTANCE "$TESTS" 2> /dev/null
+R=$?
+if [[ $R -ne 0 ]] ; then
+    echo "Test failed, rerunning with debugger"
+    echo ./hcnet-core test $HCNET_CORE_TEST_PARAMS --base-instance $BASE_INSTANCE "$TESTS"
+    lldb -o 'r'  -o 'bt' -o 'exit' -- ./hcnet-core test $HCNET_CORE_TEST_PARAMS --base-instance $BASE_INSTANCE "$TESTS"
+fi
+exit $R
